---
title: "Probability, Statistics and Data - 2 Probability"
author: "RH"
date: "2023-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

# set theme used for plotting
theme_set(theme_bw(base_size = 12))
```

```{r}
sample(x = 1:10, size = 1)
sample(x = 1:10, size = 8)
# sample(x = 1:10, size = 30)
```

```{r}
sample(x = 1:10, size = 20, replace = TRUE)
sample(1:10, 20, replace = TRUE)
```

```{r}
bloodtypes <- c("O", "A", "B", "AB")
bloodprobs <- c(0.45, 0.40, 0.11, 0.04)
sample(x = bloodtypes, size = 30, prob = bloodprobs, replace = TRUE)
```

```{r}
sim_data <- sample(
  x = bloodtypes, size = 10000,
  prob = bloodprobs, replace = TRUE
)
table(sim_data)

table(sim_data) / 10000
```

## 2.2.2 

```{r}
die1 <- sample(x = 1:6, size = 10000, replace = TRUE)
die2 <- sample(x = 1:6, size = 10000, replace = TRUE)
sumDice <- die1 + die2

head(die1)
head(die2)
head(sumDice)
```
```{r}
eventE <- sumDice == 6
head(eventE)
mean(eventE)
round(5/36, 4)

eventF <- die1 == 2 | die2 == 2
head(eventF)
mean(eventF)
round(11/36, 4)

mean(eventE & eventF)
mean((sumDice == 6) & (die1 == 2 | die2 == 2))
round(2/36, 4)

mean((sumDice == 6) | (die1 == 2 | die2 == 2))
round(14/36, 4)
```
##2.2.3 Using replicate to repeat experiments

#example 2.11
```{r}
dice <- sample(x = 1:6, size = 7, replace = TRUE) # roll seven dice
sum(dice) > 30 # test if the event occurred

replicate(20, {
  dice <- sample(x = 1:6, size = 7, replace = TRUE) # roll seven dice
  sum(dice) > 30 # test if the event occurred
})

event <- replicate(10000, {
  dice <- sample(x = 1:6, size = 7, replace = TRUE) # roll seven dice
  sum(dice) > 30 # test if the event occurred
})
mean(event)


```
#example 2.12
```{r}
die_roll <- sample(1:6, 3, TRUE)
max(die_roll) == 4

replicate(20, {
  die_roll <- sample(1:6, 3, TRUE)
  max(die_roll) == 4
})

event <- replicate(10000, {
  die_roll <- sample(1:6, 3, TRUE)
  max(die_roll) == 4
})
mean(event)
```

#example 2.13
```{r}
mean(replicate(10, {
  sum(sample(1:6, 2, T)) == 6
}))

mean(replicate(200, {
  sum(sample(1:6, 2, T)) == 6
}))

mean(replicate(10000, {
  sum(sample(1:6, 2, T)) == 6
}))
```

```{r}
n_step <- 100
trials <- c(seq(10,2000,20), seq(2000, 10000, n_step))
# trials <- c(10,20)

c(seq(1, 200, 2), seq(200, 1000, 10))
seq(10,2000,20)
seq(2000, 10000, n_step)

trials

n <- NULL
p_6 <- NULL

for (n in trials) {
  # print(n)
  p_n6 <- NULL
  p_n6 <- mean(replicate(n, {
    sum(sample(1:6, 2, T)) == 6
  }))
  p_6 <- c(p_6, p_n6)
  # print(p_6)
}

# plot(trials, p_6)
```

```{r}
sum_6 <- tibble(
  n_trials = trials,
  p_trials = p_6
)

ggplot(sum_6, aes(x = n_trials, y = p_trials)) +
  geom_point() +
  geom_hline(aes(yintercept = 0.138888), color = "red")
```


# 2.14
```{r}
coinToss <- sample(c("H", "T"), 10, replace = TRUE)
coinToss

sum(coinToss == "H")

sum(coinToss == "H") == 3

coinToss[1:9]

sum(coinToss[1:9] == "H") == 2

sum(coinToss == "H") == 3 & sum(coinToss[1:9] == "H") == 2

event <- replicate(10000, {
  coinToss <- sample(c("H", "T"), 10, replace = TRUE)
  (sum(coinToss == "H") == 3) & (sum(coinToss[1:9] == "H") == 2)
})

mean(event)

sum(coinToss == "H") == 3 & coinToss[10] == "H"

sum(coinToss[1:9] == "H") == 2 & coinToss[10] == "H"
```

#2.15
```{r}
sample_size <- 25

birthdays <- sample(x = 1:365, size = sample_size, replace = TRUE)
birthdays

anyDuplicated(birthdays)
birthdays[anyDuplicated((birthdays))]

eventB <- replicate(n = 10000, {
  birthdays <- sample(x = 1:365, size = 25, replace = TRUE)
  anyDuplicated(birthdays) > 0
})
mean(eventB)
```
#2.16
```{r}
event <- replicate(10000, {
  x <- sort(runif(3, 0, 1))
  sum(x[1:2]) > x[3]
})
# runif, 3 random numbers between 0 and 1
# sum, sum number of index 1 to 2 that are greather than index 3
mean(event)

```

#2.17
```{r}

# If you buy a bag from the New Jersey factory that contains 35 M&M’s, what is the probability that it will contain exactly 9 Blue and 5 Red M&M’s?
 
# To do this, we can use the prob argument in the sample function, as follows.

mm_colors <- c("Blue", "Orange", "Green", "Yellow", "Red", "Brown")
mm_probs <- c(25, 25, 12.5, 12.5, 12.5, 12.5)
bag <- sample(
  x = mm_colors,
  size = 35,
  replace = TRUE,
  prob = mm_probs
)
sum(bag == "Blue") # counts the number of Blue M&M's
mean(bag == "Blue")



event <- replicate(10000, {
  bag <- sample(
    x = mm_colors,
    size = 35,
    replace = TRUE,
    prob = mm_probs
  )
  sum(bag == "Blue") == 9 & sum(bag == "Red") == 5
})
mean(event)
```




##Test
```{r}
mean(replicate(10000, {
  sum(sample(1:6, 2, T)) == 2
  
}))

tester <- sample(1:5)
tester
max(tester)
sum(tester) == 15

?sample
?max
?sum
```

##2.3 Conditional probability and independence

#Example 2.26
```{r}
mean(replicate(10000, {
  roll5 <- sample(1:6, 5, replace = TRUE)
  any(roll5 == 6)
}))
```

##2.3.2 Simulating conditional probability

#Example 2.27
```{r}
eventAB <- replicate(10000, {
  dieRoll <- sample(1:6, 2, replace = TRUE)
  (sum(dieRoll) >= 10) && (6 %in% dieRoll)
})
probAB <- mean(eventAB)
probAB

eventB <- replicate(10000, {
  die_roll <- sample(1:6, 2, replace = TRUE)
  6 %in% die_roll
})
probB <- mean(eventB)
probB

probAB / probB
5/11
```

