---
title: "R_for_Data-Schience_Wrangler_13_16"
author: "RH"
date: "2023-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(dplyr.summarise.inform = FALSE)


library(tidyverse)

library(lubridate)
library(nycflights13)

# set theme used for plotting
theme_set(theme_bw(base_size = 12))
```

##13.2 nycflights13
```{r}
airlines
airports
planes
weather
```

##13.3 Keys
```{r}
planes %>% 
  count(tailnum) %>% 
  filter(n > 1)

weather %>% 
  count(year, month, day, hour, origin) %>% 
  filter(n > 1)
```


```{r}
flights %>% 
  count(year, month, day, flight) %>% 
  filter(n > 1)

flights %>% 
  count(year, month, day, tailnum) %>% 
  filter(n > 1)
```

##13.4 Mutating Joins
```{r}
flights2 <- flights %>% 
  select(year:day, hour, origin, dest, tailnum, carrier)
flights2
```

```{r}
flights2 %>%
  select(-origin, -dest) %>% 
  left_join(airlines, by = "carrier")
```

```{r}
flights2 %>%
  select(-origin, -dest) %>% 
  mutate(name = airlines$name[match(carrier, airlines$carrier)])
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3"
)
```

```{r}
x %>% 
  inner_join(y, by = "key")
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     1, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2"
)
left_join(x, y, by = "key")
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     3, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     2, "y3",
     3, "y4"
)
left_join(x, y, by = "key")
```

```{r}
flights2 %>% 
  left_join(weather)
```

```{r}
flights2
planes
flights2 %>% 
  left_join(planes, by = "tailnum")
```

```{r}
flights2
airports

flights2 %>% 
  left_join(airports, c("dest" = "faa"))

flights2 %>% 
  left_join(airports, c("origin" = "faa"))
```

##13.5 Filtering Joins
```{r}
top_dest <- flights %>%
  count(dest, sort = TRUE) %>%
  head(10)
top_dest
```

```{r}
flights
flights %>% 
  filter(dest %in% top_dest$dest)
```

```{r}
flights %>% 
  semi_join(top_dest)
```

```{r}
flights %>%
  anti_join(planes, by = "tailnum") %>%
  count(tailnum, sort = TRUE)
```

##13.6 Join problems
```{r}
airports %>% count(alt, lon) %>% filter(n > 1)
```

##13.7 Set operations
```{r}
df1 <- tribble(
  ~x, ~y,
   1,  1,
   2,  1
)
df2 <- tribble(
  ~x, ~y,
   1,  1,
   1,  2
)

df1
df2
```

```{r}
intersect(df1, df2)

union(df1, df2)

setdiff(df1, df2)

setdiff(df2, df1)
```

> setdiff er gott at kanna um tvær col eru líka, um tær eru so fært tú eina 0 aftur.

```{r}
setdiff(df1, df1)
```

##14.2 String basics
```{r}
string1 <- "This is a string"
string2 <- 'If I want to include a "quote" inside a string, I use single quotes'
```

```{r}
double_quote <- "\"" # or '"'
single_quote <- '\'' # or "'"

escape_quote <- "\"" # or '"'
writeLines(escape_quote)
```

```{r}
str <- "we are the so-called \"vikings\", from the north."
str
writeLines(str)
```

```{r}
x <- c("\"", "\\")
x

writeLines(x)
```

```{r}
x <- "\u00b5"
x
```

```{r}
c("one", "two", "three")
```

```{r}
str_length(c("a", "R for data science", NA))
```

```{r}
str_c("x", "y")

str_c("x", "y", "z")
```

```{r}
str_c("x", "y", sep = ", ")
```

```{r}
x <- c("abc", NA)
str_c("|-", x, "-|")

str_c("|-", str_replace_na(x), "-|")
```

```{r}
str_c("prefix-", c("a", "b", "c"), "-suffix")
```

```{r}
name <- "Hadley"
time_of_day <- "morning"
birthday <- FALSE

str_c(
  "Good ", time_of_day, " ", name,
  if (birthday) " and HAPPY BIRTHDAY",
  "."
)
```

```{r}
str_c(c("x", "y", "z"), collapse = ", ")
```

```{r}
x <- c("Apple", "Banana", "Pear")
str_sub(x, 1, 3)

str_sub(x, -3, -1)
```

```{r}
str_sub("a", 1, 5)
```

```{r}
str_sub(x, 1, 1) <- str_to_lower(str_sub(x, 1, 1))
```

```{r}
# Turkish has two i's: with and without a dot, and it
# has a different rule for capitalising them:

str_to_upper(c("i", "ı"))

str_to_upper(c("i", "ı"), locale = "tr")

```

```{r}
x <- c("apple", "eggplant", "banana")

str_sort(x, locale = "en")  # English

str_sort(x, locale = "haw") # Hawaiian
```

##14.3 Matching patterns with regular expressions
```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")
```

##15.2 Creating factors
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")
```

```{r}
x2 <- c("Dec", "Apr", "Jam", "Mar")
```

```{r}
sort(x1)
```

```{r}
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)
```

```{r}
y1 <- factor(x1, levels = month_levels)
y1

sort(y1)
```
```{r}
y2 <- factor(x2, levels = month_levels)
y2
```

```{r}
y2 <- parse_factor(x2, levels = month_levels)
```

```{r}
factor(x1)
```

```{r}
f1 <- factor(x1, levels = unique(x1))
f1

f2 <- x1 %>% factor() %>% fct_inorder()
f2
```

```{r}
levels(f2)
```

##15.3 General Social Survey
```{r}
gss_cat
```

```{r}
gss_cat %>%
  count(race)
```

```{r}
ggplot(gss_cat, aes(race)) +
  geom_bar()
```

```{r}
ggplot(gss_cat, aes(race)) +
  geom_bar() +
  scale_x_discrete(drop = FALSE)
```

##15.4 Modifying factor order
```{r}
relig_summary <- gss_cat %>%
  group_by(relig) %>%
  summarise(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )

ggplot(relig_summary, aes(tvhours, relig)) + geom_point()
```

```{r}
ggplot(relig_summary, aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()
```

```{r}
relig_summary %>%
  mutate(relig = fct_reorder(relig, tvhours)) %>%
  ggplot(aes(tvhours, relig)) +
    geom_point()
```

```{r}
rincome_summary <- gss_cat %>%
  group_by(rincome) %>%
  summarise(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )

ggplot(rincome_summary, aes(age, fct_reorder(rincome, age))) + geom_point()
```

```{r}
ggplot(rincome_summary, aes(age, fct_relevel(rincome, "Not applicable"))) +
  geom_point()
```

```{r}
by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  count(age, marital) %>%
  group_by(age) %>%
  mutate(prop = n / sum(n))

ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)

ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")
```

```{r}
gss_cat %>%
  ggplot(aes(marital))+
  geom_bar()

gss_cat %>%
  mutate(marital = marital %>% fct_infreq()) %>%
  ggplot(aes(marital)) +
    geom_bar()

gss_cat %>%
  mutate(marital = marital %>% fct_infreq() %>% fct_rev()) %>%
  ggplot(aes(marital)) +
    geom_bar()
```

## 15.5 Modifying factor levels
```{r}
gss_cat %>% count(partyid)
```

```{r}
gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat"
  )) %>%
  count(partyid)
```

```{r}
gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat",
    "Other"                 = "No answer",
    "Other"                 = "Don't know",
    "Other"                 = "Other party"
  )) %>%
  count(partyid)
```

```{r}
gss_cat %>%
  mutate(partyid = fct_collapse(partyid,
    other = c("No answer", "Don't know", "Other party"),
    rep = c("Strong republican", "Not str republican"),
    ind = c("Ind,near rep", "Independent", "Ind,near dem"),
    dem = c("Not str democrat", "Strong democrat")
  )) %>%
  count(partyid)
```

```{r}
gss_cat %>%
  mutate(relig = fct_lump(relig)) %>%
  count(relig)
```

```{r}
gss_cat %>%
  mutate(relig = fct_lump(relig, n = 10)) %>%
  count(relig, sort = TRUE) %>%
  print(n = Inf)
```

## 16.2 Create date/times
```{r}
today()

now()
```

```{r}
ymd("2017-01-31")

mdy("January 31st, 2017")

dmy("31-Jan-2017")
```

```{r}
ymd(20170131)
```

```{r}
ymd_hms("2017-01-31 20:11:59")

mdy_hm("01/31/2017 08:01")
```

```{r}
ymd(20170131, tz = "UTC")
```

