---
title: "5 Data Transformation"
author: "RH"
date: "2023-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(dplyr.summarise.inform = FALSE)

# install.packages("tidyverse")
# install.packages(c("gapminder", "Lahman", "nycflights13", "palmerpenguins", "wakefield"))

library(nycflights13)
library(tidyverse)
```


## 5.2 Filter rows with filter*()
```{r}
# filter(flights, month == 1, day==1)
jan1 <- filter(flights, month == 1, day == 1)
jan1

(dec25 <- filter(flights, month == 12, day == 25))
```

```{r}
sqrt(2) ^ 2 == 2
#> [1] FALSE
1 / 49 * 49 == 1
#> [1] FALSE
```
```{r}
near(sqrt(2) ^ 2,  2)
#> [1] TRUE
near(1 / 49 * 49, 1)
#> [1] TRUE
```
```{r}
# November or December
filter(flights, month == 11 | month == 12)

nov_dec <- filter(flights, month %in% c(11, 12))
nov_dec
```

```{r}
filter(flights, !(arr_delay > 120 | dep_delay > 120))
filter(flights, arr_delay <= 120, dep_delay <= 120)

```
```{r}
x <- NA
is.na(x)
#> [1] TRUE
```
```{r}
df <- tibble(x = c(1, NA, 3))
filter(df, x > 1)
filter(df, is.na(x) | x > 1)
```

# 5.3 Arrange rows with arrange()
```{r}
arrange(flights, year, month, day)
arrange(flights, desc(dep_delay))

```

5.4 Select Cloumns with select()
```{r}
# Select columns by name
select(flights, year, month, day)

# Select all columns between year and day (inclusive)
select(flights, year:day)

# Select all columns except those from year to day (inclusive)
select(flights, -(year:day))
```
```{r}
select(flights, time_hour, air_time, everything())
```


5.5 Add new variables with mutate()

```{r}
# %/% integer division
# %% Modular arithmetic - modulus

transmute(flights,
  dep_time,
  hour = dep_time %/% 100,
  minute = dep_time %% 100
)
```

5.6
```{r}
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
summarise(flights, delay = mean(dep_delay, na.rm = FALSE))
```
```{r}
batting <- as_tibble(Lahman::Batting)

batters <- batting %>%
  group_by(playerID) %>%
  summarise(
    ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE),
    ab = sum(AB, na.rm = TRUE)
  )

batters %>%
  filter(ab > 100) %>%
  ggplot(mapping = aes(x = ab, y = ba))+
  geom_point()+
  geom_smooth(se=FALSE)
```

```{r}
x <- seq(10, 1, -1)

x

first(x)
min(x)
nth(x, 4)
nth(x, 11, default = 0)
last(x)

range(x)
range(x)[1]
range(x)[2]
```
```{r}
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))
```


```{r}
maxima_departure_times <- 
  not_cancelled %>%
  group_by(year, month, day) %>%
  mutate(r = min_rank(desc(dep_time))) %>%
  filter(r %in% range(r)) %>%
  
  # select(r, everything())
  select(-r)

arrange(maxima_departure_times, year, month, day, dep_time)
```

```{r}
min_departure_times <- 
  not_cancelled %>%
  group_by(year,month,day)%>%
  slice_min(dep_time, n=1)

min_departure_times


max_departure_times <- 
  not_cancelled %>%
  group_by(year,month,day)%>%
  slice_max(dep_time, n=1)

max_departure_times


minmax_departure_times <- 
  rbind(min_departure_times, max_departure_times)

arrange(minmax_departure_times, year, month, day, dep_time)

setdiff(maxima_departure_times, minmax_departure_times)

```

