---
title: "5 Data Transformation"
author: "RH"
date: "2023-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(dplyr.summarise.inform = FALSE)

# install.packages("tidyverse")
# install.packages(c("gapminder", "Lahman", "nycflights13", "palmerpenguins", "wakefield"))

library(nycflights13)
library(tidyverse)
```


## 5.2 Filter rows with filter*()
```{r}
# filter(flights, month == 1, day==1)
jan1 <- filter(flights, month == 1, day == 1)
jan1

(dec25 <- filter(flights, month == 12, day == 25))
```

```{r}
sqrt(2) ^ 2 == 2
#> [1] FALSE
1 / 49 * 49 == 1
#> [1] FALSE
```
```{r}
near(sqrt(2) ^ 2,  2)
#> [1] TRUE
near(1 / 49 * 49, 1)
#> [1] TRUE
```
```{r}
# November or December
filter(flights, month == 11 | month == 12)

nov_dec <- filter(flights, month %in% c(11, 12))
nov_dec
```

```{r}
filter(flights, !(arr_delay > 120 | dep_delay > 120))
filter(flights, arr_delay <= 120, dep_delay <= 120)

```
```{r}
x <- NA
is.na(x)
#> [1] TRUE
```
```{r}
df <- tibble(x = c(1, NA, 3))
filter(df, x > 1)
filter(df, is.na(x) | x > 1)
```

# 5.3 Arrange rows with arrange()
```{r}
arrange(flights, year, month, day)
arrange(flights, desc(dep_delay))

```

5.4 Select Cloumns with select()
```{r}
# Select columns by name
select(flights, year, month, day)

# Select all columns between year and day (inclusive)
select(flights, year:day)

# Select all columns except those from year to day (inclusive)
select(flights, -(year:day))
```
```{r}
select(flights, time_hour, air_time, everything())
```


5.5 Add new variables with mutate()

```{r}
# %/% integer division
# %% Modular arithmetic - modulus

transmute(flights,
  dep_time,
  hour = dep_time %/% 100,
  minute = dep_time %% 100
)
```

5.6
```{r}
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
summarise(flights, delay = mean(dep_delay, na.rm = FALSE))
```
```{r}
batting <- as_tibble(Lahman::Batting)

batters <- batting %>%
  group_by(playerID) %>%
  summarise(
    ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE),
    ab = sum(AB, na.rm = TRUE)
  )

batters %>%
  filter(ab > 100) %>%
  ggplot(mapping = aes(x = ab, y = ba))+
  geom_point()+
  geom_smooth(se=FALSE)
```

```{r}
x <- seq(10, 1, -1)

x

first(x)
min(x)
nth(x, 4)
nth(x, 11, default = 0)
last(x)

range(x)
range(x)[1]
range(x)[2]
```
```{r}
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))
```


```{r}
maxima_departure_times <- 
  not_cancelled %>%
  group_by(year, month, day) %>%
  mutate(r = min_rank(desc(dep_time))) %>%
  filter(r %in% range(r)) %>%
  
  # select(r, everything())
  select(-r)

arrange(maxima_departure_times, year, month, day, dep_time)
```

```{r}
min_departure_times <- 
  not_cancelled %>%
  group_by(year,month,day)%>%
  slice_min(dep_time, n=1)

min_departure_times


max_departure_times <- 
  not_cancelled %>%
  group_by(year,month,day)%>%
  slice_max(dep_time, n=1)

max_departure_times


minmax_departure_times <- 
  rbind(min_departure_times, max_departure_times)

arrange(minmax_departure_times, year, month, day, dep_time)

setdiff(maxima_departure_times, minmax_departure_times)

```

## 5.4 Central Limit Theorem
```{r}
n <-100

Xbar <- mean(rpois(n, 2))
(Xbar - 2) / (sqrt(2) / sqrt(n))

Z <- replicate(10000, {
  Xbar <- mean(rpois(n, 2))
  (Xbar - 2) / (sqrt(2) / sqrt(n))
})

ndata <- tibble(
  x = seq(-4,4,0.1),
  y = dnorm(x, 0, 1)
)

ggplot() +
  geom_density(aes(x = Z)) +
  geom_line(data=ndata, aes(x = x, y = y), color = "red")
```

```{r}
n <-5000

Z <- replicate(10000, {
  Xbar <- mean(rexp(n, 1/3))
  (Xbar - 3) / (3 / sqrt(n))
})

ndata <- tibble(
  x = seq(-4,4,0.1),
  y = dnorm(x, 0, 1)
)

ggplot() +
  geom_density(aes(x = Z)) +
  geom_line(data=ndata, aes(x = x, y = y), color = "red")

```

```{r}
# Start with lots of zeros
skewdata <- replicate(2000, 0)
# Add a few moderately sized values
skewdata <- c(skewdata, rexp(200, 1 / 10))
# Add a few large values
skewdata <- c(skewdata, seq(100000, 500000, 50000))

mu <- mean(skewdata)
sig <- sd(skewdata)


n <- 1000

Z <- replicate(10000, {
  Xbar <- mean(sample(skewdata, n, TRUE))
  (Xbar - mu) / (sig / sqrt(n))
})

ndata <- tibble(
  x = seq(-4, 4, 0.1),
  y = dnorm(x, 0, 1)
)

ggplot() +
  geom_histogram(aes(x = Z, y = after_stat(density)),
                 binwidth = 1,
                 color = "black", fill = "lightgray" ) +
  geom_line(data=ndata, aes(x = x, y = y), colour = "red")
```

```{r}
# Check the remark below defining 5.24

df1 <- 2
df2 <- 3

# random sample 10000 values from chi-distribution with 2 def
X <- rchisq(10000, df1)
# random sample 10000 values from chi-distribution with 3 def
Y <- rchisq(10000, df2)

df <- df1 + df2

chidata <- tibble(
  x = seq(0,25,0.1),
  y = dchisq(x, df)
)

# Density
ggplot() +
  geom_density(aes(x = X + Y)) +
  geom_line(data=chidata, aes(x = x, y = y), color ="red")
```

```{r}
n <- 4
mu <- 5
sigma <- 9

S2 <- replicate(10000, ((n-1)/sigma^2) * sd(rnorm(n, mu, sigma))^2)

chidata <- tibble(
  x = seq(0, 25, 0.1),
  y = dchisq(x, n -1)
)

# Density
ggplot() +
  geom_histogram(aes(x = S2, y = after_stat(density)),
                 binwidth = 1,
                 color = "black", fill = "lightgray") +
  geom_line(data=chidata, aes(x = x, y = y), color = "red")
```

```{r}
t <- replicate(10000, {
  X <- rnorm(6,3,4)
  (mean(X) - 3) / (sd(X) / sqrt(6))
})

n <- 6

tdata <- tibble(
  x = seq(-10, 10, 0.1),
  y = dt(x, n -1)
)

# Density
ggplot() +
  geom_histogram(aes(x = t, y = after_stat(density)),
                 binwidth = 1,
                 color = "black", fill = "lightgray") +
  geom_line(data=tdata, aes(x = x, y = y), color = "red")
```

## 5.6 Point estimators
```{r}
# Example 5.30 (unbiased estimator)

# 5 random samples from a normal distribution with mean 1 and variance of 4
mean(rnorm(5,1,2))

mean(replicate(10000, mean(rnorm(5,1,2))))

```
```{r}
# Example 5.31

# Estimate variance 
sd(rnorm(5,1,2))^2

mean(replicate(10000, sd(rnorm(5,1,2))^2))
```

```{r}
# Example 5.32

n <- 5
mu <- 1
sd <- 2

# biased estimator of sd^2
replicate(
  7,
  mean(replicate(10000, {
    X <- rnorm(n, mu, sd)
    (1 / n) * sum((X - mean(X))^2)
  }))
)

# unbiased estimator of sd^2
replicate(
  7,
  mean(replicate(10000, {
    X <- rnorm(n, mu, sd)
    (1 / (n-1)) * sum((X - mean(X))^2)
  }))
)

```

```{r}
# Example 5.33

n <- 10
mu <- 1
sd <- 2

# biased estimator of sd^2
S <- replicate(
  7,
  mean(replicate(10000, {
    X <- rnorm(n, mu, sd)
    sd(X)
  }))
)

# MSE
mean((S - mu)^2)

# Bias S - sd_givid
bias_estimate <- mean(replicate(10000, {
  x <- rnorm(n, mu, sd)
  s <- sd(x)
  (s - sd)
}))

# Variance
variant_estimate <- var(replicate(10000, {
  x <- rnorm(n, mu, sd)
  s <- sd(x)
  (s - sd)
}))
bias_estimate^2 + variant_estimate

```

```{r}
# Example 3.34

n <- 20
mu <- 0
sd <- 2

# biased estimator of sd^2
s2 <- replicate(10000, {
    X <- rnorm(n, mu, sd)
    var(X)
  })

# MSE
mean((s2 - sd^2)^2)

# sí bók
var(s2)

# Bias S - sd_givid
hat_sigma2 <- replicate(10000, {
  x <- rnorm(n, mu, sd)
  xbar <- mean(x)
  1 / 20 * sum((x - xbar)^2)
})
var(hat_sigma2)

mean(hat_sigma2 -4)

var(hat_sigma2) - mean(hat_sigma2 - 4)^2

mean((hat_sigma2 - 4)^2)


```

```{r}
# MSE for the unbiased estimator
mean((s2 - 4)^2)

# MSE for biased estimator iw lower
mean((hat_sigma2 - 4)^2)

# Variance of unbiased estimator
var(s2)

# Variance of the biased estimator is lower
var(hat_sigma2)

```

